### ISSUE TITLE
Best architecture from paper

### ISSUE THREAD

**Issue by ZFTurbo** [karnwatcharasupat/bandit#1]
Hello. I'm experimenting with your repository. There are a lot of weights available. Can you please point on the weights which gives best score on DnR test set?

I downloaded "dnr-3s-mus64-l1snr-plus.ckpt" and use config "bsrnn-small-dnr-multi-mus64.yaml". Is this correct?

**Comment by kwatcharasupat** [comment]
Yep, that is the best model.
