### ISSUE TITLE
How do i setup this?

### ISSUE THREAD

**Issue by FlashlightET** [karnwatcharasupat/bandit#4]
What python version is required specifically, and modules required to run. Torch version? Cuda version? ai tends to be really finicky with versions and compatibility. I can't seem to get an environment set up for this.

**Comment by FlashlightET** [comment]
I am so dumb there is an environment.yaml

**Comment by austinpharper** [comment]
@FlashlightET, can you help me out?

I have installed everything from the environment.yaml list, and I downloaded and unzipped the DnR and MUSDB18-HQ datasets. But I'm not sure what the Readme means by "run each dataset's respective proprocess.py." I don't see any python scripts in the dataset files.
I'm also not sure what the next two lines mean.
```
python train.py expt/path-to-the-desired-experiment.yaml.
python test.py expt/path-to-the-desired-experiment.yaml --ckpt_path=path/to/checkpoint-from-training.ckpt.

```
