### ISSUE TITLE
Error when trying to run on 6 seconds wav file

### ISSUE THREAD

**Issue by BankNatchapol** [karnwatcharasupat/bandit#8]
I'm using `dnr-3s-mus64-l1snr-plus.ckpt ` with `dnr-3s-mus64-l1snr.yaml`
and it returns this error
```
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (485100, 485100) at dimension 2 of input [1, 1, 298205]
```

**Comment by BankNatchapol** [comment]
In `bandit/core/utils/audio.py` BaseFader, I added this into prepare method for temporary fix.
```
def prepare(self, audio):
        if self.edge_frame_pad_sizes[0] > audio.shape[-1]:
                self.edge_frame_pad_sizes = (audio.shape[-1]-1, audio.shape[-1]-1)
```

**Comment by kwatcharasupat** [comment]
Hi Bank, 

Adjusting the edge like that might affect the overlap add. The edge frame pad sizes have theoretical implications on perfect reconstruction with Hann window.

For the quickest fix, I would suggest switching the padding mode to "zero".

The slightly more appropriate way is to pad like you do using reflect, then use zero for the rest of the required padding size. 

FYI: This is an older version of the code kept for reproducibility and I will be only maintaining bandit-v2 beginning in September or so.

**Comment by BankNatchapol** [comment]
> Hi Bank,
> 
> Adjusting the edge like that might affect the overlap add. The edge frame pad sizes have theoretical implications on perfect reconstruction with Hann window.
> 
> For the quickest fix, I would suggest switching the padding mode to "zero".
> 
> The slightly more appropriate way is to pad like you do using reflect, then use zero for the rest of the required padding size.
> 
> FYI: This is an older version of the code kept for reproducibility and I will be only maintaining bandit-v2 beginning in September or so.

Thank you so much for your response. 
And also for your amazing work!
